services:
  powershell_container:
    image: ghcr.io/krx3d/powershelldocker:latest
    container_name: powershell_container
    environment:
      - POWERSHELL_TELEMETRY_OPTOUT=1
      - EXTRA_SOFTWARE="python3"  # Add extra software if needed
    volumes:
      - /mnt/user/powershell-scripts:/scripts
    restart: "no"
